title: Luighi Viton-Zorrilla
email: lv@luighiviton.com
description: >- # this means to ignore newlines until "baseurl:"
    This is is my personal web page. It describes my professional 
    trajectory and the projects I have developed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luighiviton.com" 
twitter_username: LuighiVZ
github_username:  LuighiV
linkedin_username: luighiviton

#Google Analytics
google_analytics: G-99CDQ0YY10

#SEO info
tagline: A personal web page of Luighi Viton-Zorrilla
author: Luighi Viton-Zorrilla
twitter:
  username: LuighiVZ
  card: summary_large_image
logo: /images/logo.png
social:
  name: Luighi Viton-Zorrilla
  links:
    - https://www.linkedin.com/in/luighiviton
    - https://www.twitter.com/LuighiVZ
    - https://github.com/LuighiV

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - env/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

header_pages:
  en:
    - index.md
    - en/profile.md
    - en/skills.md
    - en/experience.md
    - en/projects/index.md
    - en/courses.md
    - en/publications.md
    - en/volunteering.md
    - en/contact.md
  es:
    - es/index.md
    - es/profile.md
    - es/skills.md
    - es/experience.md
    - es/projects/index.md
    - es/courses.md
    - es/publications.md
    - es/volunteering.md
    - es/contact.md
  pt:
    - pt/index.md
    - pt/profile.md
    - pt/skills.md
    - pt/experience.md
    - pt/projects/index.md
    - pt/courses.md
    - pt/publications.md
    - pt/volunteering.md
    - pt/contact.md

defaults:
    -
     scope:
         path: es
     values:
         lang: es
         base_url: "/es/"
         description: >-
            Esta es mi página web personal. Esta página describe mi trayectoria 
            profesional y los proyectos que he desarrollado.
         tagline: Página web personal de Luighi Vitón Zorrilla
         image: /images/banner-es.png
    -
     scope:
         path: pt
     values:
         lang: pt
         base_url: "/pt/"
         description: >-
            Este é meu site pessoal. Esta página descreve minha trajetória
            profissional e os projetos que desenvolvi.
         tagline: Site pessoal de Luighi Vitón Zorrilla
         image: /images/banner-pt.png
    -
     scope:
         path: en
     values:
         lang: en
         base_url: "/en/"
         home_url: "/"
         image: /images/banner.png
