title: Luighi Viton-Zorrilla
email: lv@luighiviton.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal web page of Luighi Viton-Zorrilla. I'm an electronic engineer,
  enthusiastic programmer and passionate about learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LuighiVZ
github_username:  LuighiV
linkedin_username: luighiviton

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

header_pages:
  en:
    - index.md
    - en/profile.md
    - en/skills.md
    - en/experience.md
    - en/projects/index.md
    - en/publications.md
    - en/volunteering.md
    - en/contact.md
  es:
    - es/index.md
    - es/profile.md
    - es/skills.md
    - es/experience.md
    - es/projects/index.md
    - es/publications.md
    - es/volunteering.md
    - es/contact.md

defaults:
    -
     scope:
         path: es
     values:
         lang: es
         base_url: "/es/"
    -
     scope:
         path: en
     values:
         lang: en
         base_url: "/en/"
         home_url: "/"
